## Vectors, Matrices, and Arrays

### Creating a Vector

In [1]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

In [2]:
vector_column

array([[1],
       [2],
       [3]])

In [3]:
vector_row

array([1, 2, 3])

### Creating a Matrix

In [4]:
# Load library
import numpy as np

# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [5]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [6]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])

In [7]:
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

###  Creating a Sparse Matrix

In [8]:
# Load libraries
import numpy as np
from scipy import sparse

# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

Sparse matrices only store nonzero elements and assume all other values will be zero, leading to significant computational savings.

In [9]:
# View sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [10]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [12]:
# View original sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [13]:
# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


### Selecting Elements

In [14]:
# Load library
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select third element of vector
vector[2]

3

In [15]:
# Select second row, second column
matrix[1,1]

5

In [16]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [17]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [18]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [19]:
# Select the last element
vector[-1]

6

In [20]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

### Describing a Matrix

In [22]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# View number of rows and columns
matrix.shape

(3, 4)

In [23]:
# View number of elements (rows * columns)
matrix.size

12

In [24]:
# View number of dimensions
matrix.ndim

2

### Applying Operations to Elements

In [25]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [26]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

### Finding the Maximum and Minimum Values

In [31]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 6, 5],
                   [7, 8, 9]])

# Return maximum element
np.max(matrix)

9

In [32]:
# Return minimum element
np.min(matrix)

1

In [33]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [34]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

###  Calculating the Average, Variance, and Standard Deviation

In [35]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return mean
np.mean(matrix)

5.0

In [36]:
# Return variance
np.var(matrix)

6.666666666666667

In [37]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [38]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

### Reshaping Arrays

In [47]:
# Load library
import numpy as np

# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [40]:
matrix.size

12

One useful argument in reshape is -1, which effectively means “as many as needed,” so reshape(-1, 1) means one row and as many columns as needed:

In [46]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [43]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Transposing a Vector or Matrix

In [49]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

a vector cannot be transposed because it is just a collection of values:

In [50]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [51]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### Flattening a Matrix

You need to transform a matrix into a one-dimensional array.

In [52]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# or 
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Finding the Rank of a Matrix (linalg)

In [54]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# Return matrix rank
np.linalg.matrix_rank(matrix)

2

### Calculating the Determinant (linalg)

In [55]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
# 1 * (36 - 48) - 2 * (18 - 18) + 3 * (16 - 12)
# - 12 + 12 = 0

# Return determinant of matrix
np.linalg.det(matrix)

0.0

### Getting the Diagonal of a Matrix

In [56]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [57]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [58]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

### Calculating the Trace of a Matrix

In [59]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return trace
matrix.trace()

14

In [60]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

### Finding Eigenvalues and Eigenvectors (linalg)

In [61]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [62]:
eigenvalues, eigenvectors

(array([13.55075847,  0.74003145, -3.29078992]),
 array([[-0.17622017, -0.96677403, -0.53373322],
        [-0.435951  ,  0.2053623 , -0.64324848],
        [-0.88254925,  0.15223105,  0.54896288]]))

### Calculating Dot Products

In [63]:
# Load library
import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
np.dot(vector_a, vector_b)


32

in Python 3.5+ we can use the new @ operator:

In [64]:
# Calculate dot product
vector_a @ vector_b

32

### Adding and Subtracting Matrices

In [66]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [67]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [68]:
# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

### Multiplying Matrices

In [70]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])

# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [71]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

### Inverting a Matrix

In [72]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])

# Calculate inverse of matrix
np.linalg.inv(matrix)


array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

$ AA^1=I $

In [73]:
# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

### Generating Random Values

In [76]:
# Load library
import numpy as np

# Set seed
np.random.seed(2)

# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.4359949 , 0.02592623, 0.54966248])

In [77]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([2, 8, 7])

In [78]:
# Draw three numbers from a normal distribution 
# with mean 0.0 
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.07445552, -0.61722311, -1.50100687])

In [79]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-1.01077978,  0.49436355,  0.11670064])

In [80]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.13457995, 1.51357812, 1.18443987])