### 2. Introduction to TensorFlow Primitives

#### Basic Computations in TensorFlow

In [1]:
import tensorflow as tf
tf.InteractiveSession()

/Users/hakan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.zeros(2)

<tf.Tensor 'zeros:0' shape=(2,) dtype=float32>

In [3]:
tf.zeros((2,))

<tf.Tensor 'zeros_1:0' shape=(2,) dtype=float32>

In [4]:
tf.zeros((2,2))

<tf.Tensor 'zeros_2:0' shape=(2, 2) dtype=float32>

In [5]:
a = tf.zeros(2)
a.eval()

array([0., 0.], dtype=float32)

In [12]:
a.get_shape()

TensorShape([Dimension(2)])

In [13]:
a.name

'zeros_3:0'

In [14]:
a.shape

TensorShape([Dimension(2)])

In [15]:
a = tf.zeros((2, 3))
a.eval()

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [16]:
a = tf.zeros((2,2, 3))
>>> a.eval()

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [17]:
b = tf.ones((2,2,2))
>>> b.eval()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [18]:
b = tf.fill((2, 2), 5.)
b.eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [19]:
b = tf.fill((2, 2), value=5.)
b.eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [20]:
a = tf.constant(3)
a

<tf.Tensor 'Const:0' shape=() dtype=int32>

In [21]:
a = tf.constant(3)
a.eval()

3

In [22]:
a = tf.constant(3, dtype=tf.int64)
a.eval()

3

In [23]:
a = tf.constant(3,dtype=tf.float64)
a.eval()

3.0

#### Sampling Random Tensors

In [24]:
a = tf.random_normal((2, 2), mean=0, stddev=1)
>>> a.eval()

array([[ 1.1244916,  1.0629476],
       [-1.1428417,  0.314597 ]], dtype=float32)

In [25]:
a = tf.random_uniform((2, 2), minval=-2, maxval=2)
>>> a.eval()

array([[ 1.4510102, -1.0693307],
       [-1.8053031, -1.1464515]], dtype=float32)

#### Tensor Addition and Scaling

In [26]:
c = tf.ones((2, 2))

In [27]:
d = tf.ones((2, 2))

In [28]:
e = c + d

In [29]:
e.eval()

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [30]:
e

<tf.Tensor 'add:0' shape=(2, 2) dtype=float32>

In [31]:
f = 2 * e

In [32]:
f.eval()

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [33]:
c = tf.fill((2,2), 2.)

In [34]:
d = tf.fill((2,2), 7.)

In [35]:
e = c * d

In [36]:
e.eval()

array([[14., 14.],
       [14., 14.]], dtype=float32)

#### Matrix Operations

In [38]:
# Creating an identity matrix
a = tf.eye(4)
a.eval()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [39]:
r = tf.range(1, 5, 1)
r.eval()

array([1, 2, 3, 4], dtype=int32)

In [40]:
d = tf.diag(r)
d.eval()

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]], dtype=int32)

In [41]:
a = tf.ones((2, 3))
a.eval()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [42]:
at = tf.matrix_transpose(a)
at.eval()

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [43]:
a = tf.ones((2, 3))
>>> a.eval()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [44]:
b = tf.ones((3, 4))
>>> b.eval()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [45]:
c = tf.matmul(a, b)
c

<tf.Tensor 'MatMul:0' shape=(2, 4) dtype=float32>

In [46]:
c.eval()

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)

In [48]:
c = a @ b
c

<tf.Tensor 'matmul_1:0' shape=(2, 4) dtype=float32>

In [49]:
c.eval()

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)

#### Tensor Types

* tf.float32
* tf.float64
* tf.int32
* tf.int64

Casting:

* tf.to_double()
* tf.to_float()
* tf.to_int32() 
* tf.to_int64()

In [50]:
a = tf.ones((2,2), dtype=tf.int32)
>>> a.eval()

array([[1, 1],
       [1, 1]], dtype=int32)

In [51]:
b = tf.to_float(a)
>>> b.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

#### Tensor Shape Manipulations

In [52]:
a = tf.ones(8)
a.eval()

array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [53]:
b = tf.reshape(a, (4, 2))
b.eval()

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [54]:
c = tf.reshape(a, (2, 2, 2))
c.eval()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [55]:
a = tf.ones(2)
>>> a.get_shape()

TensorShape([Dimension(2)])

In [59]:
a

<tf.Tensor 'ones_8:0' shape=(2,) dtype=float32>

In [56]:
a.eval()

array([1., 1.], dtype=float32)

In [60]:
b = tf.expand_dims(a, 0)
b

<tf.Tensor 'ExpandDims:0' shape=(1, 2) dtype=float32>

In [61]:
b.eval()

array([[1., 1.]], dtype=float32)

In [62]:
b.get_shape()

TensorShape([Dimension(1), Dimension(2)])

In [63]:
c = tf.expand_dims(a, 1)

In [64]:
c

<tf.Tensor 'ExpandDims_1:0' shape=(2, 1) dtype=float32>

In [65]:
c.eval()

array([[1.],
       [1.]], dtype=float32)

In [66]:
d = tf.squeeze(b)
d

<tf.Tensor 'Squeeze:0' shape=(2,) dtype=float32>

In [67]:
d.eval()

array([1., 1.], dtype=float32)

In [69]:
e = tf.squeeze(b, 1)
e

ValueError: Can not squeeze dim[1], expected a dimension of 1, got 2 for 'Squeeze_2' (op: 'Squeeze') with input shapes: [1,2].

In [70]:
e = tf.squeeze(b, 0)
e

<tf.Tensor 'Squeeze_3:0' shape=(2,) dtype=float32>

#### Introduction to Broadcasting

In [71]:
a = tf.ones((2, 2))
>>> a.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [74]:
b = tf.range(0, 2, 1, dtype=tf.float32)
>>> b.eval()

array([0., 1.], dtype=float32)

In [76]:
b

<tf.Tensor 'range_3:0' shape=(2,) dtype=float32>

In [75]:
c = a + b
c.eval()

array([[1., 2.],
       [1., 2.]], dtype=float32)

In [77]:
b = tf.range(0, 2, 1)
b.eval()

array([0, 1], dtype=int32)

In [78]:
c = a + b

ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 'Tensor("range_4:0", shape=(2,), dtype=int32)'

### Imperative and Declarative Programming

In [80]:
# TensorFlow program declaratively performing an addition
a = tf.constant(3)
b = tf.constant(4)
c = a + b
c

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [81]:
c.eval()

7

#### TensorFlow Graphs

In [82]:
tf.get_default_graph()

When a tf.Graph is not explicitly specified, TensorFlow adds tensors and operations to a hidden global tf.Graph instance.

#### TensorFlow Sessions

In [83]:
sess = tf.Session()
a = tf.ones((2, 2))
b = tf.matmul(a, a)
b.eval(session=sess)

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [84]:
>>> sess.run(b)

array([[2., 2.],
       [2., 2.]], dtype=float32)

#### TensorFlow Variables

In [85]:
a = tf.Variable(tf.ones((2, 2)))
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32_ref>

In [86]:
a.eval()

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: _retval_Variable_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

In [87]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
a.eval(session=sess)

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [88]:
sess.run(a.assign(tf.zeros((2,2))))

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [89]:
sess.run(a)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [90]:
sess.run(a.assign(tf.zeros((3,3))))

ValueError: Dimension 0 in both shapes must be equal, but are 2 and 3. Shapes are [2,2] and [3,3]. for 'Assign_1' (op: 'Assign') with input shapes: [2,2], [3,3].